### PR TITLE
Improves readability

### PR DESCRIPTION
**Pull request by TheZitroX**
You do it **everywhere** - **stop using c code in cpp pls.**
Use the **iostream** instead of **_stdio.h._**
I don't even look at the code anymore - I just indent it, so my coworker can read it better for practice.

### CODE REVIEW

**Comment by jondurrant** [comment]
Reverting code to former coding standards. "{" are not on new lines.

**Comment by TheZitroX** [comment]
i know it blows up the code with some more lines, but the readability gets way better, i would take a try

**Comment by TheZitroX** [comment]
btw - use tab as spaces (2 or 4) - it will help with foramtting the code with commentations ect.

**Comment by jondurrant** [comment]
Best practice is use spaces I think. Tabs default to 2, 4 or 8. Most IDEs
encode as spaces.

Jon

**Pull request merged**
